### ISSUE TITLE
Building Go Example From Latest version is not working

### ISSUE THREAD

**Issue by mabuaisha** [openfaas/templates#201] opened 2020-03-19 07:59 UTC
Right now if I'm using the latest version for template and try to run build go template it will failed on this line `faas-cli build -yaml gofunction.yml`

https://github.com/openfaas/templates/commit/360077eb041d6c6474580d99814bee1b908124b7#diff-4d556a797de20381a5772bb2d63961a3R20 with the following error

```
cat: can't open 'function/GO_REPLACE.txt': No such file or directory
```

**Comment by alexellis** [comment] 2020-03-19 08:47
Hi @mabuaisha I'm going to close this because I can't reproduce it.

If you feel there's an error, then, please fill out the whole issue template with how to reproduce this. 

Alex

**Comment by alexellis** [comment] 2020-03-19 08:47
The issue template is not optional, it's for your benefit as much as ours - https://github.com/openfaas/templates/blob/master/.github/ISSUE_TEMPLATE.md

**Closed by alexellis** 2020-03-19 08:47 UTC

**Comment by mabuaisha** [comment] 2020-03-19 08:49
@alexellis Sure Alex, will give a try and for issue template next time will follow it and many thanks for your fast response on this, I really appreciate that

**Comment by alexellis** [comment] 2020-03-19 11:44
You can edit the issue and I'll reopen if you can give us instructions to reproduce a failing error mid-build due to the file not existing. As @LucasRoesler has shown, we are not able to see that error right now.
